### ISSUE TITLE
getThumbs will be deprecated, use getThumbnails instead

### ISSUE THREAD

**Issue by tofkamp** [UniversalViewer/uv-hello-world#2]
I have installed this on my iipserver. Downloaded the example manifest file from http://wellcomelibrary.org/iiif/b18035723/manifest and put it on my own server.
Downloaded the latest uv-alpha, compiled it, and put also on the same server. Modified the index.html to point to the local (copied) manifest.
When I open the http://server/index.html on in my local workstation browser, it works. But I get the warning message "getThumbs will be deprecated, use getThumbnails instead" in the console(F12) in edge windows 10. I also get the same warning in IE.

**Comment by edsilv** [comment]
That's fine, it's just a warning in the manifesto library to advise users of it (such as the UV) that `Sequence.getThumbs` will change to `Sequence.getThumbnails` in future. `Sequence.getThumbails` uses `canvas.getThumbnail` - which is in line with how you'd get a thumbnail for other resources in your manifest.
