### ISSUE TITLE
"npm i" not finishing successfully

### ISSUE THREAD

**Issue by minusdavid** [UniversalViewer/uv-hello-world#3]
I'm getting this error when I'm running "npm i":

npm WARN lifecycle uv-hello-world@1.0.0~postinstall: cannot run in wd %s %s (wd=%s) uv-hello-world@1.0.0 rm -rf uv && cp -R node_modules/universalviewer/uv uv /root/uv-hello-world

If I just run "cp -R node_modules/universalviewer/uv uv" by hand in /root/uv-hello-world, then it works fine.

**Comment by edsilv** [comment]
I've pushed a change to use rimraf instead of `rm -rf` (have noticed permissions errors with that before). Does that help?

**Comment by ghost** [comment]
???????????  Please remove me from this group or whatever it is. I am not interested in anything to do with a subscription or whatever this is!

Vicki Satta

**Comment by minusdavid** [comment]
Sorry for the delay, Edward. Thanks for that. Much better!
